services:
  php-build:
    image: "php:${PHP_VERSION:-8.2}-cli"
    command: ["sh", "/srv/php-lib/.docker/setup.sh", "${AWS_ACCESS_KEY_ID}", "${AWS_SECRET_ACCESS_KEY}"]
    stdin_open: true
    volumes:
      - ~/.aws/:/root/.aws:ro
      - ./:/srv/php-lib
