version: "3.8"

services:
  php-build:
    image: "php:${PHP_VERSION:-7.1}-cli"
    command: ["sh", "/srv/php-lib/.docker/setup.sh", "${AWS_ACCESS_KEY_ID}", "${AWS_SECRET_ACCESS_KEY}"]
    stdin_open: true
    volumes:
      - ./:/srv/php-lib
